% Object-Oriented Polarization Software (OOPS)
% Copyright (C) 2026 William Dean
% SPDX-License-Identifier: GPL-3.0-or-later

function presets = viewPresets()
%VIEWPRESETS Describe paired panel content without owning graphics or UI state.
% Kind identifies the content renderer used by each panel source. The persisted
% left/right settings remain the current source choices,
% so manually editing either dropdown does not leave a stale preset identity.
% Definition order determines the order of entries in the View menu.

% Ordered view definitions describing each panel's content without graphics handles.
presets(1) = struct( ...
    'Name',"Files", ...
    'Left',struct('Kind',"Image",'Source',"Input"), ...
    'Right',struct('Kind',"Image",'Source',"Calibration"));

presets(2) = struct( ...
    'Name',"Mask", ...
    'Left',struct('Kind',"Image",'Source',"Average intensity"), ...
    'Right',struct('Kind',"Image",'Source',"Mask"));

presets(3) = struct( ...
    'Name',"Order", ...
    'Left',struct('Kind',"Image",'Source',"Average intensity"), ...
    'Right',struct('Kind',"Image",'Source',"Order"));

presets(4) = struct( ...
    'Name',"Azimuth", ...
    'Left',struct('Kind',"Image",'Source',"Average intensity"), ...
    'Right',struct('Kind',"Image",'Source',"Azimuth"));

presets(5) = struct( ...
    'Name',"Plots", ...
    'Left',struct('Kind',"Plot",'Source',"Scatterplot"), ...
    'Right',struct('Kind',"Plot",'Source',"Swarmplot"));

presets(6) = struct( ...
    'Name',"Objects", ...
    'Left',struct('Kind',"Image",'Source',"Average intensity"), ...
    'Right',struct('Kind',"ObjectGrid",'Source',"Objects"));
end
