function [hAx,hImg] = imageDisplayTest()


    fH = uifigure("HandleVisibility","on",...
        "WindowStyle","alwaysontop",...
        "Name","Colormap Designer",...
        "Position",[0 0 500 500],...
        "Visible","off");

    hAx = uiaxes(fH,...
        "XLim",[0.5 2.5],...
        "YLim",[0.5 2.5]...
        );

    imageData = [0 64;128 255];


    hImg = image(imageData,...
        "Parent",hAx,...
        "CDataMapping","direct");


    movegui(fH,'center');
    fH.Visible = 'On';

end