function hPatch = Cpatch(X,Y,Z,C)
% helper function to plot a surf with CData
% temporary function to help plot a curve (x,y,z) where each point is associated with a value
hPatch = patch('XData',X,...
    'YData',Y,...
    'ZData',Z,...
    'CData',C,...
    'FaceColor','none',...
    'EdgeColor','interp',...  % Use interpolated color for edges
    'LineWidth', 10);
end