function TableOut = GetImageObjectSummary(cImage)

    OOPSDataOut = struct(...
        'Area',0,...
        'AvgReferenceChannelIntensity',0,...
        'AzimuthAverage',0,...
        'AzimuthStd',0,...
        'BGAverage',0,...
        'BoundingBox',[],...
        'Centroid',[],...
        'Circularity',0,...
        'ConvexArea',0,...
        'Eccentricity',0,...
        'EquivDiameter',0,...
        'Extent',0,...
        'LabelName','',...
        'MajorAxisLength',0,...
        'MaxFeretDiameter',0,...
        'MinFeretDiameter',0,...
        'MinorAxisLength',0,...
        'ObjectIdx',0,...
        'OFAvg',0,...
        'Orientation',0,...
        'Perimeter',0,...
        'PixelIdxList',[],...
        'SBRatio',0,...
        'SignalAverage',0,...
        'Solidity',0,...
        'SubarrayIdx',{}...
        );
    
    for i = 1:cImage.nObjects
        OOPSDataOut(i).Area =  cImage.Object(i).Area;
        OOPSDataOut(i).AvgReferenceChannelIntensity = cImage.Object(i).AvgReferenceChannelIntensity;
        OOPSDataOut(i).AzimuthAverage = cImage.Object(i).AzimuthAverage;
        OOPSDataOut(i).AzimuthStd = cImage.Object(i).AzimuthStd;
        OOPSDataOut(i).BGAverage =  cImage.Object(i).BGAverage;
        OOPSDataOut(i).BoundingBox = cImage.Object(i).BoundingBox;
        OOPSDataOut(i).Centroid = cImage.Object(i).Centroid;
        OOPSDataOut(i).Circularity =  cImage.Object(i).Circularity;
        OOPSDataOut(i).ConvexArea =  cImage.Object(i).ConvexArea;
        OOPSDataOut(i).Eccentricity =  cImage.Object(i).Eccentricity;
        OOPSDataOut(i).EquivDiameter = cImage.Object(i).EquivDiameter;
        OOPSDataOut(i).Extent = cImage.Object(i).Extent;
        OOPSDataOut(i).LabelName =  cImage.Object(i).LabelName;
        OOPSDataOut(i).MajorAxisLength = cImage.Object(i).MajorAxisLength;
        OOPSDataOut(i).MaxFeretDiameter =  cImage.Object(i).MaxFeretDiameter;
        OOPSDataOut(i).MinFeretDiameter =  cImage.Object(i).MinFeretDiameter;
        OOPSDataOut(i).MinorAxisLength = cImage.Object(i).MinorAxisLength;
        OOPSDataOut(i).ObjectIdx = cImage.Object(i).SelfIdx;
        OOPSDataOut(i).OFAvg =  cImage.Object(i).OFAvg;
        OOPSDataOut(i).Orientation = cImage.Object(i).Orientation;
        OOPSDataOut(i).Perimeter =  cImage.Object(i).Perimeter;
        OOPSDataOut(i).PixelIdxList = cImage.Object(i).PixelIdxList;
        OOPSDataOut(i).SBRatio = cImage.Object(i).SBRatio;
        OOPSDataOut(i).SignalAverage =  cImage.Object(i).SignalAverage;
        OOPSDataOut(i).Solidity = cImage.Object(i).Solidity;
        OOPSDataOut(i).SubarrayIdx = cImage.Object(i).SubarrayIdx;
    end % end groups
    
    TableOut = struct2table(OOPSDataOut);
    clear OOPSDataOut
end