function TableOut = GetImageObjectSummary(cImage)
%----------------------------------------------------------------------------------------------------------------------------
%
%   Object-Oriented Polarization Software (OOPS)
%   Copyright (C) 2023  William Dean
% 
%   This program is free software: you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation, either version 3 of the License, or
%   (at your option) any later version.
% 
%   This program is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
% 
%   You should have received a copy of the GNU General Public License
%   along with this program.  If not, see https://www.gnu.org/licenses/.
%
%----------------------------------------------------------------------------------------------------------------------------

    OOPSDataOut = struct(...
        'GroupIdx',0,...
        'GroupName',[],...
        'ImageIdx',0,...
        'ImageName',[],...
        'ObjectIdx',0,...
        'Area',0,...
        'AzimuthAngularDeviation',0,...
        'AzimuthAverage',0,...
        'AzimuthStd',0,...
        'BGAverage',0,...
        'Circularity',0,...
        'ConvexArea',0,...
        'Eccentricity',0,...
        'EquivDiameter',0,...
        'Extent',0,...
        'LabelName','',...
        'MajorAxisLength',0,...
        'MaxFeretDiameter',0,...
        'MidlineLength',0,...
        'MidlineRelativeAzimuth',0,...
        'MinFeretDiameter',0,...
        'MinorAxisLength',0,...
        'NormalRelativeAzimuth',0,...
        'OrderAvg',0,...
        'Perimeter',0,...
        'SBRatio',0,...
        'SignalAverage',0,...
        'Solidity',0,...
        'Tortuosity',0);


    for i = 1:cImage.nObjects

            % get the object
            thisObject = cImage.Object(i);

            % add group, image, and object names/idxs to the table
            OOPSDataOut(i).GroupIdx = OOPSData.CurrentGroupIndex;
            OOPSDataOut(i).GroupName = CurrentGroup.GroupName;
            OOPSDataOut(i).ImageIdx = thisObject.Parent.SelfIdx;
            OOPSDataOut(i).ImageName = thisObject.Parent.rawFPMShortName;
            OOPSDataOut(i).ObjectIdx = i;

            % add object data to the table for each property
            OOPSDataOut(i).Area = thisObject.Area;
            OOPSDataOut(i).AzimuthAngularDeviation = thisObject.AzimuthAngularDeviation;
            OOPSDataOut(i).AzimuthAverage = thisObject.AzimuthAverage;
            OOPSDataOut(i).AzimuthStd = thisObject.AzimuthStd;
            OOPSDataOut(i).BGAverage = thisObject.BGAverage;
            OOPSDataOut(i).Circularity = thisObject.Circularity;
            OOPSDataOut(i).ConvexArea = thisObject.ConvexArea;
            OOPSDataOut(i).Eccentricity = thisObject.Eccentricity;
            OOPSDataOut(i).EquivDiameter = thisObject.EquivDiameter;
            OOPSDataOut(i).Extent = thisObject.Extent;
            OOPSDataOut(i).LabelName = thisObject.LabelName;
            OOPSDataOut(i).MajorAxisLength = thisObject.MajorAxisLength;
            OOPSDataOut(i).MaxFeretDiameter = thisObject.MaxFeretDiameter;
            OOPSDataOut(i).MidlineLength = thisObject.MidlineLength;
            OOPSDataOut(i).MidlineRelativeAzimuth = thisObject.MidlineRelativeAzimuth;
            OOPSDataOut(i).MinFeretDiameter = thisObject.MinFeretDiameter;
            OOPSDataOut(i).MinorAxisLength = thisObject.MinorAxisLength;
            OOPSDataOut(i).NormalRelativeAzimuth = thisObject.NormalRelativeAzimuth;
            OOPSDataOut(i).OrderAvg = thisObject.OrderAvg;
            OOPSDataOut(i).Perimeter = thisObject.Perimeter;
            OOPSDataOut(i).SBRatio = thisObject.SBRatio;
            OOPSDataOut(i).SignalAverage = thisObject.SignalAverage;
            OOPSDataOut(i).Solidity = thisObject.Solidity;
            OOPSDataOut(i).Tortuosity = thisObject.Tortuosity;

    end % end groups
    
    TableOut = struct2table(OOPSDataOut);
    clear OOPSDataOut
end