function hPolarHistogram = PolarHistogramColorChart_demo(axialData)

    % duplicate and wrap the axial data over the interval [0 2*pi]
    axialData(axialData<0) = axialData(axialData<0) + pi;
    axialData = [axialData,axialData+pi];

    colormaps_mat_file = load('Colormaps.mat');
    Colormaps = colormaps_mat_file.Colormaps;

    % create a figure to hold the histogram, store the handle
    hFig = uifigure(...
        'WindowStyle','alwaysontop',...
        'Units','pixels',...
        'Position',[0 0 600 600],...
        'Color',[1 1 1],...
        'HandleVisibility','on',...
        'Visible','off'...
        );

    % create the polar histogram in the figure
    hPolarHistogram = PolarHistogramColorChart(...
        'Parent',hFig,...
        'polarData',axialData,...
        'wedgeColors',Colormaps.hsv.Map,...
        'wedgeColorsRepeats',2,...
        'nBins',48,...
        'BackgroundColor',[1 1 1],...
        'thetaGridlinesColor',[0.9 0.9 0.9],...
        'thetaGridlinesLineWidth',0.5,...
        'rGridlinesColor',[0.9 0.9 0.9],...
        'wedgeEdgeColor','interp',...
        'wedgeFaceColor','interp',...
        'wedgeLineWidth',2,...
        'wedgeFaceAlpha',0.5,...
        'circleBackgroundColor',[1 1 1],...
        'circleColor',[0 0 0],...
        'Title','Polar histogram demo');

    % move figure to window center
    movegui(hFig,'center')

    hFig.Visible = 'on';

end