function TableOut = GetImageObjectSummary(cImage)

    PODSDataOut = struct('Area',0,...
        'AvgReferenceChannelIntensity',0,...
        'AzimuthAverage',0,...
        'AzimuthStd',0,...
        'BGAverage',0,...
        'BoundingBox',[],...
        'Centroid',[],...
        'Circularity',0,...
        'ConvexArea',0,...
        'Eccentricity',0,...
        'EquivDiameter',0,...
        'Extent',0,...
        'LabelName','',...
        'MajorAxisLength',0,...
        'MaxFeretDiameter',0,...
        'MinFeretDiameter',0,...
        'MinorAxisLength',0,...
        'ObjectIdx',0,...
        'OFAvg',0,...
        'Orientation',0,...
        'Perimeter',0,...
        'PixelIdxList',[],...
        'SBRatio',0,...
        'SignalAverage',0,...
        'Solidity',0,...
        'SubarrayIdx',{});
    
    for i = 1:cImage.nObjects
        PODSDataOut(i).Area =  cImage.Object(i).Area;
        PODSDataOut(i).AvgReferenceChannelIntensity = cImage.Object(i).AvgReferenceChannelIntensity;
        PODSDataOut(i).AzimuthAverage = cImage.Object(i).AzimuthAverage;
        PODSDataOut(i).AzimuthStd = cImage.Object(i).AzimuthStd;
        PODSDataOut(i).BGAverage =  cImage.Object(i).BGAverage;
        PODSDataOut(i).BoundingBox = cImage.Object(i).BoundingBox;
        PODSDataOut(i).Centroid = cImage.Object(i).Centroid;
        PODSDataOut(i).Circularity =  cImage.Object(i).Circularity;
        PODSDataOut(i).ConvexArea =  cImage.Object(i).ConvexArea;
        PODSDataOut(i).Eccentricity =  cImage.Object(i).Eccentricity;
        PODSDataOut(i).EquivDiameter = cImage.Object(i).EquivDiameter;
        PODSDataOut(i).Extent = cImage.Object(i).Extent;
        PODSDataOut(i).LabelName =  cImage.Object(i).LabelName;
        PODSDataOut(i).MajorAxisLength = cImage.Object(i).MajorAxisLength;
        PODSDataOut(i).MaxFeretDiameter =  cImage.Object(i).MaxFeretDiameter;
        PODSDataOut(i).MinFeretDiameter =  cImage.Object(i).MinFeretDiameter;
        PODSDataOut(i).MinorAxisLength = cImage.Object(i).MinorAxisLength;
        PODSDataOut(i).ObjectIdx = cImage.Object(i).SelfIdx;
        PODSDataOut(i).OFAvg =  cImage.Object(i).OFAvg;
        PODSDataOut(i).Orientation = cImage.Object(i).Orientation;
        PODSDataOut(i).Perimeter =  cImage.Object(i).Perimeter;
        PODSDataOut(i).PixelIdxList = cImage.Object(i).PixelIdxList;
        PODSDataOut(i).SBRatio = cImage.Object(i).SBRatio;
        PODSDataOut(i).SignalAverage =  cImage.Object(i).SignalAverage;
        PODSDataOut(i).Solidity = cImage.Object(i).Solidity;
        PODSDataOut(i).SubarrayIdx = cImage.Object(i).SubarrayIdx;
    end % end groups
    
    TableOut = struct2table(PODSDataOut);
    clear PODSDataOut
end