function NewReplicate = MakeNewReplicate()

    % Default struct() for new replicates
    NewReplicate = struct('OFAvg',0,...
                       'OFMax',0,...
                       'OFMin',0,...        
                       'FilteredOFAvg',0,...
                       'pol_shortname','',...
                       'pol_fullname','',...
                       'pol_rawdata_normalizedbystack',[],...
                       'pol_rawdata',[],...
                       'nObjects',0,...
                       'level',0,...
                       'Width',0,...
                       'Height',0,...
                       'ThresholdAdjusted',logical(0),...
                       'MaskDone',logical(0),...
                       'OFDone',logical(0),...
                       'SE','disk',...
                       'SESize',num2str(5),...
                       'SELines',num2str(4),...
                       'FilterType','Median',...
                       'Object',MakeNewObject(),...
                       'ObjectNames',{['No Objects Found']},...
                       'CurrentObjectIdx',1);    

%     % Get default fieldnames/values for replicate structure               
%     ReplicateFieldNames = fieldnames(Replicate);
%     
%     % Create NewReplicate struct() array
%     NewReplicate = struct('pol_shortname','');
%     
%     % Field names of new replicate (empty)
%     NewReplicateFieldNames = fieldnames(NewReplicate);
%     
%     % List missing fields in new replicate
%     missingIdx = find(~ismember(ReplicateFieldNames,NewReplicateFieldNames));
%     
%     % Assign missing fields to NewReplicate
%     for i = 1:length(missingIdx)
%         NewReplicate.(ReplicateFieldNames{missingIdx(i)}) = Replicate.(ReplicateFieldNames{missingIdx(i)}); 
%     end    
end