function NewObject = MakeNewObject(varargin)
%% 0 INPUTS
    % default struct for new objects
    Object = struct('Area',0,...
                    'BoundingBox',[],...
                    'Centroid',[],...
                    'Circularity',0,...
                    'ConvexArea',0,...
                    'ConvexHull',[],...
                    'ConvexImage',[],...
                    'Eccentricity',0,...
                    'Extrema',[],...
                    'FilledArea',0,...
                    'Image',[],...
                    'MajorAxisLength',0,...
                    'MinorAxisLength',0,...
                    'Orientation',0,...
                    'Perimeter',0,...
                    'PixelIdxList',[],...
                    'PixelList',[],...
                    'MaxFFCAvgIntensity',0,...
                    'MeanFFCAvgIntensity',0,...
                    'MinFFCAvgIntensity',0,...
                    'BGPixelIdxList',[],...
                    'MeanBGIntensity',0,...
                    'LocalSBRatio',0,...
                    'RawPixelValues',[],...
                    'OFPixelValues',[],...
                    'AzimuthPixelValues',[],...
                    'AnisotropyPixelValues',[],...
                    'OFAvg',0,...
                    'OFMin',0,...
                    'OFMax',0,...
                    'Name','',...
                    'OriginalIdx',0);
                
    if nargin == 0
        NewObject = Object;
        return
    end                
            
%% 1 INPUT
%  Will simply add missing default fieldnames/values to input struct()  

    % 'New' object is input struct()
    NewObject = varargin{1};
                
    % Get default fieldnames/values for default Object structure               
    ObjectFieldNames = fieldnames(Object);
    
    % Field names of 'new' object
    NewObjectFieldNames = fieldnames(NewObject);
    
    % List missing fields in NewObject
    missingIdx = find(~ismember(ObjectFieldNames,NewObjectFieldNames));
    
    % Assign missing fields to NewObject
    for i = 1:length(missingIdx)
        NewObject.(ObjectFieldNames{missingIdx(i)}) = Object.(ObjectFieldNames{missingIdx(i)}); 
    end             
                
                
    return           
                
                
                
end