function TableOut = SavePODSData(source)

    PODSData = guidata(source);
    
    PODSDataOut = struct('GroupIdx',0,...
                         'GroupName',[],...
                         'ImageIdx',0,...
                         'ImageName',[],...
                         'ObjectIdx',0,...
                         'OFAvg',0,...
                         'AzimuthAverage',0,...
                         'AzimuthStd',0,...
                         'SBRatio',0,...
                         'Area',0,...
                         'Perimeter',0,...
                         'SignalAverage',0,...
                         'BGAverage',0,...
                         'Circularity',0,...
                         'Eccentricity',0,...
                         'ConvexArea',0,...
                         'MaxFeretDiameter',0,...
                         'MinFeretDiameter',0,...
                         'MajorAxisLength',0,...
                         'MinorAxisLength',0,...
                         'Orientation',0,...
                         'Solidity',0,...
                         'EquivDiameter',0,...
                         'Extent',0,...
                         'AvgReferenceChannelIntensity',0,...
                         'LabelName','',...
                         'MidlineRelativeAzimuth',0,...
                         'NormalRelativeAzimuth',0,...
                         'Tortuosity',0);

    MasterIdx = 1;
               
    for i = 1:PODSData.nGroups
        for j = 1:PODSData.Group(i).nReplicates
            for k = 1:PODSData.Group(i).Replicate(j).nObjects
                PODSDataOut(MasterIdx).GroupIdx = i;
                PODSDataOut(MasterIdx).GroupName = PODSData.Group(i).GroupName;
                PODSDataOut(MasterIdx).ImageIdx = j;
                PODSDataOut(MasterIdx).ImageName = PODSData.Group(i).Replicate(j).pol_shortname;
                PODSDataOut(MasterIdx).ObjectIdx = k;
                PODSDataOut(MasterIdx).OFAvg =  PODSData.Group(i).Replicate(j).Object(k).OFAvg;
                PODSDataOut(MasterIdx).AzimuthAverage = PODSData.Group(i).Replicate(j).Object(k).AzimuthAverage;
                PODSDataOut(MasterIdx).AzimuthStd = PODSData.Group(i).Replicate(j).Object(k).AzimuthStd;
                PODSDataOut(MasterIdx).SBRatio = PODSData.Group(i).Replicate(j).Object(k).SBRatio;
                PODSDataOut(MasterIdx).Area =  PODSData.Group(i).Replicate(j).Object(k).Area;
                PODSDataOut(MasterIdx).Perimeter =  PODSData.Group(i).Replicate(j).Object(k).Perimeter;
                PODSDataOut(MasterIdx).SignalAverage =  PODSData.Group(i).Replicate(j).Object(k).SignalAverage;
                PODSDataOut(MasterIdx).BGAverage =  PODSData.Group(i).Replicate(j).Object(k).BGAverage;
                PODSDataOut(MasterIdx).Circularity =  PODSData.Group(i).Replicate(j).Object(k).Circularity;
                PODSDataOut(MasterIdx).Eccentricity =  PODSData.Group(i).Replicate(j).Object(k).Eccentricity;
                PODSDataOut(MasterIdx).ConvexArea =  PODSData.Group(i).Replicate(j).Object(k).ConvexArea;
                PODSDataOut(MasterIdx).MaxFeretDiameter =  PODSData.Group(i).Replicate(j).Object(k).MaxFeretDiameter;
                PODSDataOut(MasterIdx).MinFeretDiameter =  PODSData.Group(i).Replicate(j).Object(k).MinFeretDiameter;
                PODSDataOut(MasterIdx).MajorAxisLength = PODSData.Group(i).Replicate(j).Object(k).MajorAxisLength;
                PODSDataOut(MasterIdx).MinorAxisLength = PODSData.Group(i).Replicate(j).Object(k).MinorAxisLength;
                PODSDataOut(MasterIdx).Orientation = PODSData.Group(i).Replicate(j).Object(k).Orientation;
                PODSDataOut(MasterIdx).Solidity = PODSData.Group(i).Replicate(j).Object(k).Solidity;
                PODSDataOut(MasterIdx).EquivDiameter = PODSData.Group(i).Replicate(j).Object(k).EquivDiameter;
                PODSDataOut(MasterIdx).Extent = PODSData.Group(i).Replicate(j).Object(k).Extent;
                PODSDataOut(MasterIdx).AvgReferenceChannelIntensity = PODSData.Group(i).Replicate(j).Object(k).AvgReferenceChannelIntensity;
                PODSDataOut(MasterIdx).LabelName =  PODSData.Group(i).Replicate(j).Object(k).LabelName;
                PODSDataOut(MasterIdx).MidlineRelativeAzimuth = PODSData.Group(i).Replicate(j).Object(k).MidlineRelativeAzimuth;
                PODSDataOut(MasterIdx).NormalRelativeAzimuth = PODSData.Group(i).Replicate(j).Object(k).NormalRelativeAzimuth;
                PODSDataOut(MasterIdx).Tortuosity = PODSData.Group(i).Replicate(j).Object(k).Tortuosity;
                MasterIdx = MasterIdx+1;
            end % end objects
        end % end images
    end % end groups
    
    TableOut = struct2table(PODSDataOut);
    clear PODSDataOut
    
end