function TableOut = SaveOOPSData(source)

    OOPSData = guidata(source);
    
    OOPSDataOut = struct('GroupIdx',0,...
                         'GroupName',[],...
                         'ImageIdx',0,...
                         'ImageName',[],...
                         'ObjectIdx',0,...
                         'OFAvg',0,...
                         'AzimuthAverage',0,...
                         'AzimuthStd',0,...
                         'SBRatio',0,...
                         'Area',0,...
                         'Perimeter',0,...
                         'SignalAverage',0,...
                         'BGAverage',0,...
                         'Circularity',0,...
                         'Eccentricity',0,...
                         'ConvexArea',0,...
                         'MaxFeretDiameter',0,...
                         'MinFeretDiameter',0,...
                         'MajorAxisLength',0,...
                         'MinorAxisLength',0,...
                         'Orientation',0,...
                         'Solidity',0,...
                         'EquivDiameter',0,...
                         'Extent',0,...
                         'AvgReferenceChannelIntensity',0,...
                         'LabelName','',...
                         'MidlineRelativeAzimuth',0,...
                         'NormalRelativeAzimuth',0,...
                         'Tortuosity',0,...
                         'MidlineLength',0,...
                         'AzimuthAngularDeviation',0);

    MasterIdx = 1;
               
    for i = 1:OOPSData.nGroups
        for j = 1:OOPSData.Group(i).nReplicates
            for k = 1:OOPSData.Group(i).Replicate(j).nObjects
                OOPSDataOut(MasterIdx).GroupIdx = i;
                OOPSDataOut(MasterIdx).GroupName = OOPSData.Group(i).GroupName;
                OOPSDataOut(MasterIdx).ImageIdx = j;
                OOPSDataOut(MasterIdx).ImageName = OOPSData.Group(i).Replicate(j).pol_shortname;
                OOPSDataOut(MasterIdx).ObjectIdx = k;
                OOPSDataOut(MasterIdx).OFAvg =  OOPSData.Group(i).Replicate(j).Object(k).OFAvg;
                OOPSDataOut(MasterIdx).AzimuthAverage = OOPSData.Group(i).Replicate(j).Object(k).AzimuthAverage;
                OOPSDataOut(MasterIdx).AzimuthStd = OOPSData.Group(i).Replicate(j).Object(k).AzimuthStd;
                OOPSDataOut(MasterIdx).SBRatio = OOPSData.Group(i).Replicate(j).Object(k).SBRatio;
                OOPSDataOut(MasterIdx).Area =  OOPSData.Group(i).Replicate(j).Object(k).Area;
                OOPSDataOut(MasterIdx).Perimeter =  OOPSData.Group(i).Replicate(j).Object(k).Perimeter;
                OOPSDataOut(MasterIdx).SignalAverage =  OOPSData.Group(i).Replicate(j).Object(k).SignalAverage;
                OOPSDataOut(MasterIdx).BGAverage =  OOPSData.Group(i).Replicate(j).Object(k).BGAverage;
                OOPSDataOut(MasterIdx).Circularity =  OOPSData.Group(i).Replicate(j).Object(k).Circularity;
                OOPSDataOut(MasterIdx).Eccentricity =  OOPSData.Group(i).Replicate(j).Object(k).Eccentricity;
                OOPSDataOut(MasterIdx).ConvexArea =  OOPSData.Group(i).Replicate(j).Object(k).ConvexArea;
                OOPSDataOut(MasterIdx).MaxFeretDiameter =  OOPSData.Group(i).Replicate(j).Object(k).MaxFeretDiameter;
                OOPSDataOut(MasterIdx).MinFeretDiameter =  OOPSData.Group(i).Replicate(j).Object(k).MinFeretDiameter;
                OOPSDataOut(MasterIdx).MajorAxisLength = OOPSData.Group(i).Replicate(j).Object(k).MajorAxisLength;
                OOPSDataOut(MasterIdx).MinorAxisLength = OOPSData.Group(i).Replicate(j).Object(k).MinorAxisLength;
                OOPSDataOut(MasterIdx).Orientation = OOPSData.Group(i).Replicate(j).Object(k).Orientation;
                OOPSDataOut(MasterIdx).Solidity = OOPSData.Group(i).Replicate(j).Object(k).Solidity;
                OOPSDataOut(MasterIdx).EquivDiameter = OOPSData.Group(i).Replicate(j).Object(k).EquivDiameter;
                OOPSDataOut(MasterIdx).Extent = OOPSData.Group(i).Replicate(j).Object(k).Extent;
                OOPSDataOut(MasterIdx).AvgReferenceChannelIntensity = OOPSData.Group(i).Replicate(j).Object(k).AvgReferenceChannelIntensity;
                OOPSDataOut(MasterIdx).LabelName =  OOPSData.Group(i).Replicate(j).Object(k).LabelName;
                OOPSDataOut(MasterIdx).MidlineRelativeAzimuth = OOPSData.Group(i).Replicate(j).Object(k).MidlineRelativeAzimuth;
                OOPSDataOut(MasterIdx).NormalRelativeAzimuth = OOPSData.Group(i).Replicate(j).Object(k).NormalRelativeAzimuth;
                OOPSDataOut(MasterIdx).Tortuosity = OOPSData.Group(i).Replicate(j).Object(k).Tortuosity;
                OOPSDataOut(MasterIdx).MidlineLength = OOPSData.Group(i).Replicate(j).Object(k).MidlineLength;
                OOPSDataOut(MasterIdx).AzimuthAngularDeviation = OOPSData.Group(i).Replicate(j).Object(k).AzimuthAngularDeviation;
                MasterIdx = MasterIdx+1;
            end % end objects
        end % end images
    end % end groups
    
    TableOut = struct2table(OOPSDataOut);
    clear OOPSDataOut
    
end