function [] = UpdateTables(source)

    PODSData = guidata(source);
    cGroupIndex = PODSData.CurrentGroupIndex;
    cGroup = PODSData.Group(cGroupIndex);
    cImageIndex = cGroup.CurrentImageIndex;
    cReplicate = cGroup.Replicate(cImageIndex);
    
    Handles = PODSData.Handles;
    
    
    
    Handles.ProjectDataTable.Text = {['<b>Project Overview</b>'];...
                                     ['Project Name:         ', PODSData.ProjectName];...
                                     ['Number of Groups:     ', num2str(PODSData.nGroups)];...
                                     ['InputFileType:        ', PODSData.Settings.InputFileType];...
                                     ['Current Tab:          ', PODSData.Settings.CurrentTab];...
                                     ['                      '];...
                                     ['<b>Current Group Summary</b>'];...
                                     ['Group Name:           ', cGroup.GroupName];...
                                     ['Number of Replicates: ', num2str(cGroup.nReplicates)];...
                                     ['                      '];...
                                     ['<b>Current Replicate Summary</b>'];...
                                     ['Current Replicate:    ', cReplicate.pol_shortname]};

    
    
    PODSData.Handles = Handles;
    
    guidata(source,PODSData);

end