function [] = UpdateTables(source)

    PODSData = guidata(source);
    cGroupIndex = PODSData.CurrentGroupIndex;
    cGroup = PODSData.Group(cGroupIndex);
    cImageIndex = cGroup.CurrentImageIndex(1);
    cReplicate = cGroup.Replicate(cImageIndex);
    
    Handles = PODSData.Handles;

    Handles.ProjectDataTable.Text = {['<b>Project Overview</b>'];...
                                     [PODSData.ProjectName];...
                                     ['Number of Groups:     ', num2str(PODSData.nGroups)];...
                                     ['Input File Type:      ', PODSData.Settings.InputFileType];...
                                     ['Current Tab:          ', PODSData.Settings.CurrentTab];...
                                     ['                      '];...
                                     ['<b>Current Group Summary</b>'];...
                                     [cGroup.GroupName];...
                                     ['Number of Replicates: ', num2str(cGroup.nReplicates)];...
                                     ['Group Avg OF:         ', num2str(cGroup.OFAvg)];,...
                                     ['                      '];...
                                     ['<b>Current Replicate Summary</b>'];...
                                     [cReplicate.pol_shortname];...
                                     ['Dimensions:           ', num2str(cReplicate.Width), 'x', num2str(cReplicate.Height)];...
                                     ['<b>Masking Parameters</b>'];...
                                     ['Mask Threshold:       ', num2str(cReplicate.level)];...
                                     ['Threshold Adjusted:   ', Logical2String(cReplicate.ThresholdAdjusted)];...
                                     ['Filter Type           ', cReplicate.FilterType];...
                                     ['SE Shape              ', cReplicate.SE];...
                                     ['SE Size               ', cReplicate.SESize, ' px'];...
                                     ['SE Lines              ', cReplicate.SELines];...
                                     ['<b>Mask Results</b>   '];...
                                     ['Number of Objects:    ', num2str(cReplicate.nObjects)];...
                                     ['<b>Order Factor Results</b>'];...
                                     ['Avg Pixel OF:         ', num2str(cReplicate.OFAvg)]};

    PODSData.Handles = Handles;
    guidata(source,PODSData);

end