% Object-Oriented Polarization Software (OOPS)
% Copyright (C) 2026 William Dean
% SPDX-License-Identifier: GPL-3.0-or-later

function [candidate,enhanced,parameters] = filaments(input,recipe)
%FILAMENTS Preserve ridge enhancement and filled zero-crossing segmentation.

% Ridge-strength image generated by fibermetric.
ridges = fibermetric(input,4);

% Accumulator retaining the strongest line-opening response at each pixel.
enhanced = zeros(size(input));

% Retain the strongest line-opening response across all tested orientations.
for angle = 1:180
    enhanced = max(enhanced,imopen(ridges,strel('line',40,angle)));
end

% Maximum line-enhanced intensity used for normalization.
peak = max(enhanced,[],'all');

if peak > 0
    enhanced = enhanced/peak;

    % Hole-filled zero-crossing foreground, or an empty mask for zero signal.
    candidate = imfill(edge(enhanced,'zerocross',0),'holes');
else
    candidate = false(size(input));
end

% Recipe snapshot for this strategy, which currently has no adjustable values.
parameters = recipe.withAutomatic(struct());
end
