function accordion = uiaccordion_demo()
%----------------------------------------------------------------------------------------------------------------------------
%
%   Object-Oriented Polarization Software (OOPS)
%   Copyright (C) 2023  William Dean
% 
%   This program is free software: you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation, either version 3 of the License, or
%   (at your option) any later version.
% 
%   This program is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
% 
%   You should have received a copy of the GNU General Public License
%   along with this program.  If not, see https://www.gnu.org/licenses/.
%
%----------------------------------------------------------------------------------------------------------------------------

    fH = uifigure(...
        "WindowStyle","alwaysontop",...
        "Name","uiaccordion demo",...
        "HandleVisibility","on",...
        "Color",[1 1 1],...
        "Position",[0 0 400 750]);

    % create a gridlayout manager to hold the accordion (it can be placed in any container, but this works best)
    accordionGrid = uigridlayout(fH,[1,1],...
        "ColumnWidth",{'1x'},...
        "RowHeight",{'fit'},...
        "Padding",[0 0 0 0],...
        "BackgroundColor",[1 1 1],...
        "Scrollable","on");

    % create the accordion and parent it to the grid
    accordion = uiaccordion(accordionGrid,...
        'ItemSpacing',3,...
        'BorderWidth',1,...
        'BorderColor',[0.8 0.8 0.8],...
        'Padding',3,...
        'BackgroundColor',[1 1 1]);


    ActiveItem = 1:5;

    %% ACCORDION ITEM 1

    % add first accordion item
    accordion.addItem("Title","Accordion item properties",...
        "BorderColor",[0.8 0.8 0.8],...
        "TitleBackgroundColor",[0.95 0.95 0.95],...
        "PaneBackgroundColor",[1 1 1],...
        "FontColor",[0 0 0],...
        "BorderWidth",1,...
        "ExpandedBorderWidth",1,...
        "TitlePadding",1);
    % set size and spacing of pane grid
    accordion.Items(1).Pane.RowHeight = repmat({'fit'},1,10);
    accordion.Items(1).Pane.ColumnWidth = {'fit','1x'};
    accordion.Items(1).Pane.RowSpacing = 5;
    accordion.Items(1).Pane.ColumnSpacing = 5;

    % drop down selector for which item we are changing
    uilabel(accordion.Items(1).Pane,"Text","Item to Modify","FontColor",[0 0 0]);
    uidropdown(...
        'Parent',accordion.Items(1).Pane,...
        'Items',{'All','1','2','3','4','5'},...
        'ItemsData',{ActiveItem,1,2,3,4,5},...
        'Value',ActiveItem,...
        'ValueChangedFcn',@changeActiveItem);

    % PaneBackgroundColor
    uilabel(accordion.Items(1).Pane,"Text","Pane Background Color","FontColor",[0 0 0]);
    uicolorpicker(...
        'Parent',accordion.Items(1).Pane,...
        'Value',[1 1 1],...
        'Tag','PaneBackgroundColor',... % accordion property controlled by this object
        'ValueChangedFcn',@setAccordionItemProperties,... % callback executed when value is changed
        "UserData",accordion.Items(1)); % accordion item stored in UserData

    % TitleBackgroundColor
    uilabel(accordion.Items(1).Pane,"Text","Title Background Color","FontColor",[0 0 0]);
    uicolorpicker(...
        'Parent',accordion.Items(1).Pane,...
        'Value',[0.95 0.95 0.95],...
        'Tag','TitleBackgroundColor',...
        'ValueChangedFcn',@setAccordionItemProperties,...
        "UserData",accordion.Items(1));

    % BorderColor
    uilabel(accordion.Items(1).Pane,"Text","Border Color","FontColor",[0 0 0]);
    uicolorpicker(...
        'Parent',accordion.Items(1).Pane,...
        'Value',[0.8 0.8 0.8],...
        'Tag','BorderColor',...
        'ValueChangedFcn',@setAccordionItemProperties,...
        "UserData",accordion.Items(1));

    % FontColor
    uilabel(accordion.Items(1).Pane,"Text","Title Font Color","FontColor",[0 0 0]);
    uicolorpicker(...
        'Parent',accordion.Items(1).Pane,...
        'Value',[0 0 0],...
        'Tag','FontColor',...
        'ValueChangedFcn',@setAccordionItemProperties,...
        "UserData",accordion.Items(1));

    % BorderWidth
    uilabel(accordion.Items(1).Pane,"Text","Border Width","FontColor",[0 0 0]);
    uieditfield(...
        accordion.Items(1).Pane,...
        "numeric",...
        "Tag","BorderWidth",...
        "ValueChangedFcn",@setAccordionItemProperties,...
        "Value",1,...
        "UserData",accordion.Items(1));

    % ExpandedBorderWidth
    uilabel(accordion.Items(1).Pane,"Text","Expanded Border Width","FontColor",[0 0 0]);
    uieditfield(...
        accordion.Items(1).Pane,...
        "numeric",...
        "Tag","ExpandedBorderWidth",...
        "ValueChangedFcn",@setAccordionItemProperties,...
        "Value",1,...
        "UserData",accordion.Items(1));

    % TitlePadding
    uilabel(accordion.Items(1).Pane,"Text","Title Padding","FontColor",[0 0 0]);
    uieditfield(...
        accordion.Items(1).Pane,...
        "numeric",...
        "Tag","TitlePadding",...
        "ValueChangedFcn",@setAccordionItemProperties,...
        "Value",1,...
        "UserData",accordion.Items(1));

    % TitleFontSize
    uilabel(accordion.Items(1).Pane,"Text","Title Font Size","FontColor",[0 0 0]);
    uieditfield(...
        accordion.Items(1).Pane,...
        "numeric",...
        "Tag","TitleFontSize",...
        "ValueChangedFcn",@setAccordionItemProperties,...
        "Value",12,...
        "UserData",accordion.Items(1));

    % ContentFontSize
    uilabel(accordion.Items(1).Pane,"Text","Content Font Size","FontColor",[0 0 0]);
    uieditfield(...
        accordion.Items(1).Pane,...
        "numeric",...
        "Tag","ContentFontSize",...
        "ValueChangedFcn",@setAccordionItemProperties,...
        "Value",12,...
        "UserData",accordion.Items(1));


    %% ACCORDION ITEM 2

    accordion.addItem("Title","Accordion properties",...
        "BorderColor",[0.8 0.8 0.8],...
        "TitleBackgroundColor",[0.95 0.95 0.95],...
        "PaneBackgroundColor",[1 1 1],...
        "FontColor",[0 0 0],...
        "BorderWidth",1,...
        "ExpandedBorderWidth",1,...
        "TitlePadding",1);
    % set size and spacing of pane grid
    accordion.Items(2).Pane.RowHeight = repmat({'fit'},1,3);
    accordion.Items(2).Pane.ColumnWidth = {'fit','1x'};
    accordion.Items(2).Pane.RowSpacing = 5;
    accordion.Items(2).Pane.ColumnSpacing = 5;

    % BackgroundColor
    uilabel(accordion.Items(2).Pane,"Text","Background Color","FontColor",[0 0 0]);
    uicolorpicker(...
        'Parent',accordion.Items(2).Pane,...
        'Value',[1 1 1],...
        'Tag','BackgroundColor',...
        'ValueChangedFcn',@setAccordionProperties,...
        "UserData",accordion);

    % BorderWidth
    uilabel(accordion.Items(2).Pane,"Text","Border Width","FontColor",[0 0 0]);
    uieditfield(...
        accordion.Items(2).Pane,...
        "numeric",...
        "ValueChangedFcn",@setAccordionProperties,...
        "Value",1,...
        "Tag","BorderWidth",...
        "UserData",accordion);

    % BorderColor
    uilabel(accordion.Items(2).Pane,"Text","Border Color","FontColor",[0 0 0]);
    uicolorpicker(...
        'Parent',accordion.Items(2).Pane,...
        'Value',[0.7 0.7 0.7],...
        'Tag','BorderColor',...
        'ValueChangedFcn',@setAccordionProperties,...
        "UserData",accordion);

    % ItemSpacing
    uilabel(accordion.Items(2).Pane,"Text","Item Spacing","FontColor",[0 0 0]);
    uieditfield(...
        accordion.Items(2).Pane,...
        "numeric",...
        "ValueChangedFcn",@setAccordionProperties,...
        "Value",3,...
        "Tag","ItemSpacing",...
        "UserData",accordion); 

    % Padding
    uilabel(accordion.Items(2).Pane,"Text","Padding","FontColor",[0 0 0]);
    uieditfield(...
        accordion.Items(2).Pane,...
        "numeric",...
        "ValueChangedFcn",@setAccordionProperties,...
        "Value",3,...
        "Tag","Padding",...
        "UserData",accordion); 



    %% ACCORDION ITEM 3

    accordion.addItem("Title","Plot type",...
        "BorderColor",[0.8 0.8 0.8],...
        "TitleBackgroundColor",[0.95 0.95 0.95],...
        "PaneBackgroundColor",[1 1 1],...
        "FontColor",[0 0 0],...
        "BorderWidth",1,...
        "ExpandedBorderWidth",1,...
        "TitlePadding",1);

    accordion.Items(3).Pane.Padding = [0 0 0 0];

    % cell array of function handles
    funHandles = {...
        @(x,a,b,c) a.*cosd(x-b)+c,...
        @(x,a,b,c) a.*(cosd(x-b).^2)+c,...
        @(x,a,b,c) a.*sind(x-b)+c,...
        @(x,a,b,c) a.*(sind(x-b).^2)+c};

    % uilistbox to select plot type
    plotTypeListBox = uilistbox(...
        accordion.Items(3).Pane,...
        "Items",{'$Y=A\cos(\theta-B)+C$','$Y=A\cos^2(\theta-B)+C$','$Y=A\sin(\theta-B)+C$','$Y=A\sin^2(\theta-B)+C$'},...
        "ItemsData",funHandles,...
        "ValueChangedFcn",@updatePlot...
        );

    % create an interpreter style and add it to the listbox
    style1 = uistyle("Interpreter",'latex');
    addStyle(plotTypeListBox,style1)


    %% ACCORDION ITEM 4
    accordion.addItem("Title","Plot parameters",...
        "BorderColor",[0.8 0.8 0.8],...
        "TitleBackgroundColor",[0.95 0.95 0.95],...
        "PaneBackgroundColor",[1 1 1],...
        "FontColor",[0 0 0],...
        "BorderWidth",1,...
        "ExpandedBorderWidth",1,...
        "TitlePadding",1);
    % set size and spacing of pane grid
    accordion.Items(4).Pane.RowHeight = {25,25,25};
    accordion.Items(4).Pane.ColumnWidth = {'fit','1x'};
    accordion.Items(4).Pane.RowSpacing = 5;
    accordion.Items(4).Pane.ColumnSpacing = 5;
    % create label and numeric editfield for each parameter
    % A
    uilabel(accordion.Items(4).Pane,"Text","A","FontColor",[0 0 0]);
    A_editfield = uieditfield(...
        accordion.Items(4).Pane,...
        "numeric",...
        "ValueChangedFcn",@updatePlot,...
        "Value",1);
    % B
    uilabel(accordion.Items(4).Pane,"Text","B","FontColor",[0 0 0]);
    B_editfield = uieditfield(...
        accordion.Items(4).Pane,...
        "numeric",...
        "ValueChangedFcn",@updatePlot);
    % C
    uilabel(accordion.Items(4).Pane,"Text","C","FontColor",[0 0 0]);
    C_editfield = uieditfield(...
        accordion.Items(4).Pane,...
        "numeric",...
        "ValueChangedFcn",@updatePlot);

    %% ACCORDION ITEM 5

    % add another accordion item to show plot
    accordion.addItem("Title","Plot",...
        "BorderColor",[0.8 0.8 0.8],...
        "TitleBackgroundColor",[0.95 0.95 0.95],...
        "PaneBackgroundColor",[1 1 1],...
        "FontColor",[0 0 0],...
        "BorderWidth",1,...
        "ExpandedBorderWidth",1,...
        "TitlePadding",1);

    hAx = uiaxes(accordion.Items(5).Pane);
    hAx.XLim = [0 360];
    hAx.Title.Interpreter = "latex";
    hAx.Title.String = "$Y=A\cos^2(\theta-B)+C$";
    hAx.XAxis.TickLabelFormat = '%g\\circ';
    hAx.XLabel.Interpreter = "latex";
    hAx.XLabel.String = "$\theta$";
    hAx.YLabel.Interpreter = "latex";
    hAx.YLabel.String = "$Y$";
    hAx.XTick = 0:45:360;

    x = 0:360;
    y = cosd(x);

    hPlot = plot(hAx,x,y);



    % expand the first accordion item
    accordion.Items(1).expand();
    % move gui to screen center
    movegui(fH,'center')
    % then shift 400 px to the left
    fH.Position(1) = fH.Position(1)-400;
    % make the figure visible
    fH.Visible = "on";

    % color change callback
    function setAccordionItemProperties(source,~)
        % % get user-selected color from color picker
        % chosenColor = uisetcolor();
        % % make sure it's valid
        % if size(chosenColor,2) == 1
        %     % if invalid, error uialert box
        %     uialert(fH,"Invalid color","Error");
        % else
        %     % if valid, set the indicated property to the chosen color
        %     source.UserData.(source.Tag) = chosenColor;
        % end

        %source.UserData.(source.Tag) = source.Value;

        set(accordion.Items(ActiveItem),source.Tag,source.Value);


    end


    function setAccordionProperties(source,~)
        source.UserData.(source.Tag) = source.Value;
    end

    % plot update callback
    function updatePlot(~,~)

        A = A_editfield.Value;
        B = B_editfield.Value;
        C = C_editfield.Value;

        hAx.Title.String = plotTypeListBox.Items{plotTypeListBox.ValueIndex};
        hPlot.YData = plotTypeListBox.Value(0:360,A,B,C);

    end


    function changeActiveItem(source,~)
        ActiveItem = source.Value;
    end


end