function hPolarHistogram = PolarHistogramColorChart_demo(axialData)
%----------------------------------------------------------------------------------------------------------------------------
%
%   Object-Oriented Polarization Software (OOPS)
%   Copyright (C) 2023  William Dean
% 
%   This program is free software: you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation, either version 3 of the License, or
%   (at your option) any later version.
% 
%   This program is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
% 
%   You should have received a copy of the GNU General Public License
%   along with this program.  If not, see https://www.gnu.org/licenses/.
%
%----------------------------------------------------------------------------------------------------------------------------

    % duplicate and wrap the axial data over the interval [0 2*pi]
    axialData(axialData<0) = axialData(axialData<0) + pi;
    axialData = [axialData,axialData+pi];

    colormaps_mat_file = load('Colormaps.mat');
    Colormaps = colormaps_mat_file.Colormaps;

    % create a figure to hold the histogram, store the handle
    hFig = uifigure(...
        'WindowStyle','alwaysontop',...
        'Units','pixels',...
        'Position',[0 0 600 600],...
        'Color',[1 1 1],...
        'HandleVisibility','on',...
        'Visible','off'...
        );

    % create the polar histogram in the figure
    hPolarHistogram = PolarHistogramColorChart(...
        'Parent',hFig,...
        'polarData',axialData,...
        'wedgeColors',Colormaps.hsv.Map,...
        'wedgeColorsRepeats',2,...
        'nBins',48,...
        'BackgroundColor',[1 1 1],...
        'thetaGridlinesColor',[0.9 0.9 0.9],...
        'thetaGridlinesLineWidth',0.5,...
        'rGridlinesColor',[0.9 0.9 0.9],...
        'wedgeEdgeColor','interp',...
        'wedgeFaceColor','interp',...
        'wedgeLineWidth',2,...
        'wedgeFaceAlpha',0.5,...
        'circleBackgroundColor',[1 1 1],...
        'circleColor',[0 0 0],...
        'Title','Polar histogram demo');

    % move figure to window center
    movegui(hFig,'center')

    hFig.Visible = 'on';

end