function hPolarHistogram = PolarHistogramColorChart_demo()
%----------------------------------------------------------------------------------------------------------------------------
%
%   Object-Oriented Polarization Software (OOPS)
%   Copyright (C) 2023  William Dean
% 
%   This program is free software: you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation, either version 3 of the License, or
%   (at your option) any later version.
% 
%   This program is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
% 
%   You should have received a copy of the GNU General Public License
%   along with this program.  If not, see https://www.gnu.org/licenses/.
%
%----------------------------------------------------------------------------------------------------------------------------

    % the demo below demonstrates how to plot angular data 
    % with pi phase ambiguity (any angle, x, is indistinguishable from x +/- pi)
    
    % generate 1000 values uniformly distributed in the range [-pi/2 pi/2]
    axialData = -pi/2 + (pi)*rand(1000,1);

    % duplicate and wrap the data over the interval [0 2*pi]
    axialData(axialData<0) = axialData(axialData<0) + pi;
    axialData = [axialData,axialData+pi];

    % create a figure to hold the histogram, store the handle
    hFig = uifigure(...
        'WindowStyle','alwaysontop',...
        'Units','pixels',...
        'Position',[0 0 600 600],...
        'Color',[1 1 1],...
        'HandleVisibility','on',...
        'Visible','off'...
        );

    % create the polar histogram in the figure
    hPolarHistogram = PolarHistogramColorChart(...
        'Parent',hFig,...
        'polarData',axialData,...
        'wedgeColors',hsv(256),...
        'wedgeColorsRepeats',2,...
        'nBins',96,...
        'BackgroundColor',[1 1 1],...
        'thetaGridlinesColor',[0.9 0.9 0.9],...
        'thetaGridlinesLineWidth',0.5,...
        'rGridlinesColor',[0.9 0.9 0.9],...
        'WedgeEdgeColor',[0 0 0],...
        'WedgeEdgeColorMode','interp',...
        'WedgeFaceColorMode','interp',...
        'WedgeLineWidth',1,...
        'WedgeFaceAlpha',0.5,...
        'CircleBackgroundColor',[1 1 1],...
        'CircleColor',[0 0 0],...
        'Title','Polar histogram demo');

    % move figure to window center
    movegui(hFig,'center')

    hFig.Visible = 'on';

end