function UpdateGUITheme(source)

    OOPSData = guidata(source);

    GUIBackgroundColor = OOPSData.Settings.GUIBackgroundColor;
    GUIForegroundColor = OOPSData.Settings.GUIForegroundColor;
    GUIHighlightColor = OOPSData.Settings.GUIHighlightColor;
    
    % get all accordion items and their children (cannot retrieve with findobj())
    accordionItems = OOPSData.Handles.SettingsAccordion.Items;
    accordionChildren = OOPSData.Handles.SettingsAccordion.Contents;
    
    % uiaccordionitem
    set(accordionItems,...
        'PaneBackgroundColor',GUIBackgroundColor,...
        'BorderColor',GUIHighlightColor,...
        'FontColor',GUIForegroundColor,...
        'TitleBackgroundColor',GUIBackgroundColor);
    
    % uiaccordion
    set(OOPSData.Handles.SettingsAccordion,...
        'BackgroundColor',GUIBackgroundColor);
    
    % uigridlayout
    set(findobj([OOPSData.Handles.fH;accordionChildren],'type','uigridlayout'),...
        'BackgroundColor',GUIBackgroundColor);
    
    % uipanel
    set(findobj([OOPSData.Handles.fH;accordionChildren],'type','uipanel'),...
        'BackgroundColor',GUIBackgroundColor,...
        'ForegroundColor',GUIForegroundColor,...
        'HighlightColor',GUIHighlightColor);
    
    % uitextarea
    set(findobj([OOPSData.Handles.fH;accordionChildren],'type','uitextarea'),...
        'FontColor',GUIForegroundColor,...
        'BackgroundColor',GUIBackgroundColor);
    
    % axes
    set(findobj([OOPSData.Handles.fH;accordionChildren],'type','axes'),...
        'XColor',GUIForegroundColor,...
        'YColor',GUIForegroundColor,...
        'Color',GUIBackgroundColor);
    
    % uilabel
    set(findobj([OOPSData.Handles.fH;accordionChildren],'type','uilabel'),...
        'FontColor',GUIForegroundColor,...
        'BackgroundColor',GUIBackgroundColor);
    
    % uitable
    set(findobj([OOPSData.Handles.fH;accordionChildren],'type','uitable'),...
        'BackgroundColor',GUIBackgroundColor,...
        'ForegroundColor',GUIForegroundColor);
    
    % uilistbox
    set(findobj([OOPSData.Handles.fH;accordionChildren],'type','uilistbox'),...
        'BackgroundColor',GUIBackgroundColor,...
        'FontColor',GUIForegroundColor);
    
    % uitree
    set(findobj([OOPSData.Handles.fH;accordionChildren],'type','uitree'),...
        'BackgroundColor',GUIBackgroundColor,...
        'FontColor',GUIForegroundColor);
    
    % set swarm plot colors
    OOPSData.Handles.ScatterPlotGrid.BackgroundColor = OOPSData.Settings.ScatterPlotBackgroundColor;
    OOPSData.Handles.ScatterPlotAxH.Color = OOPSData.Settings.ScatterPlotBackgroundColor;
    OOPSData.Handles.ScatterPlotAxH.XAxis.Color = OOPSData.Settings.ScatterPlotForegroundColor;
    OOPSData.Handles.ScatterPlotAxH.YAxis.Color = OOPSData.Settings.ScatterPlotForegroundColor;
    
    % set scatter plot colors
    OOPSData.Handles.SwarmPlotGrid.BackgroundColor = OOPSData.Settings.SwarmPlotBackgroundColor;
    OOPSData.Handles.SwarmPlotAxH.Color = OOPSData.Settings.SwarmPlotBackgroundColor;
    OOPSData.Handles.SwarmPlotAxH.XAxis.Color = OOPSData.Settings.SwarmPlotForegroundColor;
    OOPSData.Handles.SwarmPlotAxH.YAxis.Color = OOPSData.Settings.SwarmPlotForegroundColor;
    
    % set object intensity profile colors
    OOPSData.Handles.ObjectIntensityProfileGrid.BackgroundColor = OOPSData.Settings.ObjectIntensityProfileBackgroundColor;
    OOPSData.Handles.ObjectIntensityPlotAxH.Color = OOPSData.Settings.ObjectIntensityProfileBackgroundColor;
    OOPSData.Handles.ObjectIntensityPlotAxH.XAxis.Color = OOPSData.Settings.ObjectIntensityProfileForegroundColor;
    OOPSData.Handles.ObjectIntensityPlotAxH.YAxis.Color = OOPSData.Settings.ObjectIntensityProfileForegroundColor;
    OOPSData.Handles.ImgPanel2.BackgroundColor = OOPSData.Settings.ObjectIntensityProfileBackgroundColor;
    
    % set intensity slider colors
    set(OOPSData.Handles.PrimaryIntensitySlider,...
        'BackgroundColor',GUIBackgroundColor,...
        'Knob1Color',GUIForegroundColor,...
        'Knob2Color',GUIForegroundColor,...
        'RangeColor',GUIForegroundColor,...
        'MidLineColor',GUIForegroundColor,...
        'TitleColor',GUIForegroundColor);
    set(OOPSData.Handles.ReferenceIntensitySlider,...
        'BackgroundColor',GUIBackgroundColor,...
        'Knob1Color',GUIForegroundColor,...
        'Knob2Color',GUIForegroundColor,...
        'RangeColor',GUIForegroundColor,...
        'MidLineColor',GUIForegroundColor,...
        'TitleColor',GUIForegroundColor);
    
    OOPSData.Handles.CurrentThresholdLine.Color = GUIForegroundColor;
    
    OOPSData.Handles.OrderFactorAxH.Color = 'Black';
    OOPSData.Handles.AverageIntensityAxH.Color = 'Black';
    OOPSData.Handles.AzimuthAxH.Color = 'Black';
    OOPSData.Handles.MaskAxH.Color = 'Black';
    
end